import Head from 'next/head'
import Image from 'next/image'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Afrik Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<h1 className='bg-black p-4'>

Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi molestiae nam magni praesentium assumenda deserunt saepe necessitatibus dicta inventore veritatis quae earum temporibus, rerum obcaecati, expedita pariatur libero enim sit!

</h1>
   

   
    </div>
  )
}
