import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/modules/Homepage/Hero'
import Hero2 from '../components/modules/Homepage/Hero2'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Afrik Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Hero />
      <Hero2 />
      <Her0


   

   
    </div>
  )
}
