import Head from 'next/head'
import Image from 'next/image'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Afrik Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<h1 className='bg-black p-4'>


</h1>
   

   
    </div>
  )
}
